name: Render paper.pdf
on: push
jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fontist/setup-fontist@v2
      - run: fontist install "Noto Serif CJK SC"
      - uses: typst-community/setup-typst@v3
        with:
          cache-dependency-path: requirements.typ
      # Now Typst is installed and packages will be cached!
      - uses: actions/checkout@v2
      - run: |
              for file in "代数学二/main.typ" "几何学/main.typ" "复变函数/main.typ" "常微分方程/main.typ" "抽象代数/main.typ" "数学模型/main.typ"
                  do
                         typst compile $file --root . --font-path ~/.fontist/fonts
                  done
      - uses: actions/upload-artifact@v4
        with:
          name: 数学模型
          path: 数学模型/main.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: 代数学二
          path: 代数学二/main.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: 几何学
          path: 几何学/main.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: 复变函数
          path: 复变函数/main.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: 常微分方程
          path: 常微分方程/main.pdf
      - uses: actions/upload-artifact@v4
        with:
          name: 抽象代数
          path: 抽象代数/main.pdf
      
                  
