name: Render papers
on: push
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fontist/setup-fontist@v2.0.1
        with:
          fontist-version: 1.x
      - run: fontist install "Noto Serif CJK SC"

      - uses: typst-community/setup-typst@v4
        with:
          allow-prereleases: true

      - run: |
          set -eux
          mkdir -p artifacts
          # 找到所有 main.typ，排除 .github 目录
          while IFS= read -r file; do
            dir=$(dirname "$file")
            name=$(basename "$dir")
            echo "Compiling $file -> $dir/main.pdf (artifact: ${name}.pdf)"
            typst compile "$file" --root . --font-path ~/.fontist/fonts | echo "Warning: compilation of $file produced warnings/errors"
            if [ -f "$dir/main.pdf" ]; then
              cp "$dir/main.pdf" "artifacts/${name}.pdf"
            else
              echo "Warning: $dir/main.pdf not produced"
            fi
          done < <(find . -type f -name 'main.typ' -not -path './.github/*' -print)

      - uses: actions/upload-artifact@v4
        with:
          name: papers
          path: artifacts


